const data = [
  {
    key: 0,
    tintColor: '#358CDC',
    value: 0,
    minimumValue: 0,
    maximumValue: 10,
    initialValue: 1,
    stepValue: 1,
    tintOnIncrementImage: true,
    tintOnDecrementImage: true,
    incrementImage: undefined,
    decrementImage: undefined,
    disabled: false,
    wraps: true,
  },
  {
    key: 1,
    tintColor: '#32A54A',
    value: 0.99,
    minimumValue: 0,
    maximumValue: 15,
    initialValue: 0.99,
    stepValue: 0.99,
    tintOnIncrementImage: true,
    tintOnDecrementImage: true,
    incrementImage: undefined,
    decrementImage: undefined,
    disabled: false,
    wraps: false,
  },
  {
    key: 2,
    tintColor: '#cc3232',
    value: 50,
    minimumValue: -100,
    maximumValue: 100,
    initialValue: 50,
    stepValue: 25,
    tintOnIncrementImage: true,
    tintOnDecrementImage: true,
    incrementImage: undefined,
    decrementImage: undefined,
    disabled: false,
    wraps: true,
  },
  {
    key: 3,
    tintColor: '#4F3D9E',
    value: 0,
    minimumValue: -70,
    maximumValue: 70,
    initialValue: 30,
    stepValue: 10,
    tintOnIncrementImage: false,
    tintOnDecrementImage: false,
    incrementImage: 'https://facebook.github.io/react-native/docs/assets/favicon.png',
    decrementImage: 'https://facebook.github.io/react-native/docs/assets/favicon.png',
    disabled: false,
    wraps: false,
  },
];

module.exports = {
  data,
};
